/** Canonical artist story (hidden category `the-artist`, not a shop collection). */
export const ARTIST_STORY_CATEGORY_NAME = "SGphilippo";

export const ARTIST_STORY_DESCRIPTION_EN = "Some faces tell a story.\\r\\nOthers seem to carry its memory.\\r\\n\\r\\nI have always believed that a face could hide a story, long before a word is spoken.\\r\\n\\r\\nPerhaps that is why I paint women.\\r\\n\\r\\nI am a self-taught artist, but my paintings were not born from lessons or rules.\\r\\nThey were born from questions — about women, history, forgotten civilizations, symbols, memory, and those invisible stories that remain when time has erased the names.\\r\\n\\r\\nMy paintings do not seek to explain everything.\\r\\n\\r\\nA woman may appear beside an animal.\\r\\nA symbol may seem strangely familiar.\\r\\nA word may carry a meaning far deeper than it appears to hold at first glance.\\r\\n\\r\\nNothing is placed there by chance, but I prefer to leave a door slightly open for the person who looks.\\r\\n\\r\\nWhat lies behind her eyes?\\r\\nWhy this animal?\\r\\nWhy this symbol?\\r\\nAnd what happened before this moment?\\r\\n\\r\\nI do not always have the answers.\\r\\n\\r\\nI paint the face first, then I search for the story hidden behind it.\\r\\n\\r\\nSometimes, that story belongs to a forgotten era.\\r\\nSometimes, it is born from a culture, a legend, a precious stone, an ancient symbol, or simply from something I cannot explain.\\r\\n\\r\\nAnd when the painting is finished, I write its story.\\r\\n\\r\\nNot to tell the viewer what they should see, but to offer them another path into the painting.\\r\\n\\r\\nPerhaps a painting should not reveal its secret at first glance.\\r\\nPerhaps it should make you want to come closer.\\r\\n\\r\\nWelcome to my world. 🤍";

export const ARTIST_STORY_TRANSLATIONS = {
  fr: {
    name: "SGphilippo",
    description: "Certains visages racontent une histoire.\\r\\nD’autres semblent en porter la mémoire.\\r\\n\\r\\nJ’ai toujours cru qu’un visage pouvait cacher une histoire, bien avant qu’un mot ne soit prononcé.\\r\\n\\r\\nC’est peut-être pour cela que je peins les femmes.\\r\\n\\r\\nJe suis une artiste autodidacte, mais mes peintures ne sont pas nées de leçons ou de règles.\\r\\nElles sont nées de questions — sur les femmes, l’histoire, les civilisations oubliées, les symboles, la mémoire et ces récits invisibles qui demeurent lorsque le temps a effacé les noms.\\r\\n\\r\\nMes peintures ne cherchent pas à tout expliquer.\\r\\n\\r\\nUne femme peut apparaître aux côtés d’un animal.\\r\\nUn symbole peut sembler étrangement familier.\\r\\nUn mot peut porter un sens bien plus profond qu’il ne le laisse paraître au premier regard.\\r\\n\\r\\nRien n’est placé là par hasard, mais je préfère laisser une porte entrouverte à celui qui regarde.\\r\\n\\r\\nQue se cache-t-il derrière ses yeux ?\\r\\nPourquoi cet animal ?\\r\\nPourquoi ce symbole ?\\r\\nEt que s’est-il passé avant cet instant ?\\r\\n\\r\\nJe n’ai pas toujours les réponses.\\r\\n\\r\\nJe peins d’abord le visage, puis je cherche l’histoire qui se cache derrière lui.\\r\\n\\r\\nParfois, cette histoire appartient à une époque oubliée.\\r\\nParfois, elle naît d’une culture, d’une légende, d’une pierre précieuse, d’un symbole ancien ou simplement de quelque chose que je ne saurais expliquer.\\r\\n\\r\\nEt lorsque la peinture est terminée, j’en écris l’histoire.\\r\\n\\r\\nNon pas pour dire au spectateur ce qu’il doit voir, mais pour lui offrir un autre chemin vers la peinture.\\r\\n\\r\\nPeut-être qu’une peinture ne devrait pas révéler son secret au premier regard.\\r\\nPeut-être devrait-elle donner envie de s’en approcher.\\r\\n\\r\\nBienvenue dans mon univers. 🤍",
  },
} as const;
